SELECT  T.ITEM_ID AS ITEM_ID, CHILD.ITEM_NAME AS ITEM_NAME, CHILD.RARITY AS RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS PARENT ON T.PARENT_ITEM_ID = PARENT.ITEM_ID
JOIN ITEM_INFO AS CHILD ON T.ITEM_ID = CHILD.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY ITEM_ID DESC;
