-- 코드를 작성해주세요
SELECT SUB.YEAR AS YEAR, SUB.VAL-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID AS ID
FROM ECOLI_DATA AS E
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS VAL
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS SUB
ON YEAR(E.DIFFERENTIATION_DATE) = SUB.YEAR
ORDER BY YEAR, YEAR_DEV;
